version: 2.1

machine: &machine
  image: ubuntu-2004:202010-01

jobs:
  say_hello:
    machine:
      <<: *machine

    steps:
      - run: 
          name: Saying Hello 
          command: echo "Hello world"

  say_bye:
    machine:
      <<: *machine

    steps:
      - run: 
          name: Saying Bye
          command: echo "Bye"

  go_home:
    maching:
      <<: *machine

    steps:
      - run:
          name: Going home
          command: echo "going home"

workflows:
  hello_and_bye:
    jobs:
      - say_hello
      - say_bye
