version: 2.1

jobs:
  say_hello:
    machine:
      image: ubuntu-2004:202010-01

    steps:
      - run: 
        name: Saying Hello 
        command: echo "Hello world"

  say_bye:
    machine:
      image: ubuntu-2004:202010-01

    steps:
      - run: 
        name: Saying Bye
        command: echo "Bye"

workflows:
  hello_and_bye:
    jobs:
      - say_hello
      - say_bye
